# Generated by Django 4.1 on 2022-11-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obj',
            name='tags',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='obj',
            name='view_xm',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AddField(
            model_name='obj',
            name='view_xp',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AddField(
            model_name='obj',
            name='view_ym',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AddField(
            model_name='obj',
            name='view_yp',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AddField(
            model_name='obj',
            name='view_zm',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AddField(
            model_name='obj',
            name='view_zp',
            field=models.CharField(default='', max_length=240),
        ),
    ]
