# Generated by Django 4.1 on 2022-09-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datagen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datagen',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
