# Generated by Django 4.1 on 2022-09-13 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datagen', '0002_datagen_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataGen',
        ),
    ]
